name: Dockr Image CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: docker/setup-buildx-action@v1
      - name: set tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: build and push ingest
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./images/ingest/Dockerfile
          tags: ghcr.io/cownetwork/lightspeed-ingest:${{ steps.tag.outputs.tag }}
      - name: build and push webrtc
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./images/webrtc/Dockerfile
          tags: ghcr.io/cownetwork/lightspeed-webrtc:${{ steps.tag.outputs.tag }}
      - name: build and push frontend
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./images/frontend/Dockerfile
          tags: ghcr.io/cownetwork/lightspeed-frontend:${{ steps.tag.outputs.tag }}
